apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-client
  namespace: elastic
  labels:
    component: elasticsearch
    role: client
spec:
  serviceName: es-client
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-pool
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: es-client
          image: gcr.io/sqhive-backend/elastic:latest
          env:
            - name: NAMESPACE
              value: "elastic"
            - name: NODE_NAME
              value: "es-client"
            - name: NETWORK_HOST
              value: "0.0.0.0"
            - name: CLUSTER_NAME
              value: "myesdb"
            - name: NUMBER_OF_MASTERS
              value: "1"
            - name: NODE_MASTER
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: NODE_INGEST
              value: "true"
            - name: HTTP_ENABLE
              value: "true"
            - name: HTTP_CORS_ENABLE
              value: "false"
            - name: HTTP_CORS_ALLOW_ORIGIN
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
            - name: PROCESSORS
              value: "1"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          livenessProbe:
            tcpSocket:
              port: transport
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
          volumeMounts:
          - name: elastic-data-storage
            mountPath: /data
      volumes:
        - name: elastic-data-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: elastic-client-disk