apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  namespace: elastic
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: es-data
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: gcr.io/sqhive-backend/elastic:latest
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            value: "elastic"
          - name: NODE_NAME
            value: "es-data"
          - name: NETWORK_HOST
            value: "0.0.0.0"
          - name: CLUSTER_NAME
            value: "myesdb"
          - name: NUMBER_OF_MASTERS
            value: "2"
          - name: NODE_MASTER
            value: "false"
          - name: NODE_DATA
            value: "true"
          - name: NODE_INGEST
            value: "false"
          - name: HTTP_ENABLE
            value: "false"
          - name: HTTP_CORS_ENABLE
            value: "false"
          - name: HTTP_CORS_ALLOW_ORIGIN
            value: "false"
          - name: ES_JAVA_OPTS
            value: -Xms256m -Xmx256m
          - name: PROCESSORS
            value: "1"
        ports:
          - containerPort: 9300
            name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
          - name: storage
            mountPath: /data
      volumes:
        - emptyDir:
            medium: ""
          name: storage