apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: elastic
  labels:
    component: elasticsearch
    role: client
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"elastic-backend"}}'
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 80
    targetPort: 9200
