apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: elastic
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 80
    targetPort: 9200