apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kibana
  namespace: elastic
  labels:
    component: kibana
spec:
  serviceName: kibana
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: preemptible-pool
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:6.2.4
          env:
            - name: CLUSTER_NAME
              value: "myesdb"
            - name: ELASTICSEARCH_URL
              value: "http://search:80"
          ports:
            - containerPort: 5601
              name: kibana